InventoryManagementSystem/Controllers/ProductEndpoints/ProductController.cs
using IMS.Application.Interfaces;
using IMS.Application.Interfaces.IEntitiesRepo;
using IMS.Domain.Entites;
using IMS.Persistance;
using IMS.Persistance.Helper;
using IMS.Persistance.Repositories.EntitiesRepo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using static IMS.Application.Features.Product.ProductManagementModel;

namespace InventoryManagementSystem.Controllers.ProductEndpoints
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly ISubCategoryRepo subCategoryRepo;
        private readonly ISupplierRepo supplierRepo;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IProductRepo repo;
        public ProductController(ISubCategoryRepo subCategoryRepo,ISupplierRepo supplierRepo, 
            UserManager<ApplicationUser> userManager,IProductRepo repo)
        {
            this.subCategoryRepo = subCategoryRepo;
            this.supplierRepo = supplierRepo;
            this.userManager = userManager;
            this.repo = repo;
        }

       private async Task<string> CheckAuth()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);

            return user.Id;

        }

        public async Task<IActionResult> GetAllProducts()
        {

            var products = await repo.GetAllProductsAsync(await CheckAuth());
            return View(products);

        }

        [HttpGet]
        public async Task<IActionResult> AddProduct()
        {
            ViewBag.SubCategories = new SelectList(await subCategoryRepo.GetSubCategoriesRepo(), "SubCategoryId", "SubCategoryName");
            ViewBag.Suppliers = new SelectList(await supplierRepo.GetSuppliersRepo(await CheckAuth()), "SupplierId", "SupplierName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductRequest product)
        {
            if (ModelState.IsValid)
            {
                product.ApplicationUserId = await CheckAuth();
                await repo.AddProductAsync(product);
                return RedirectToAction(nameof(GetAllProducts));
            }

            ViewBag.SubCategories = new SelectList(await subCategoryRepo.GetSubCategoriesRepo(), "SubCategoryId", "SubCategoryName");
            ViewBag.Suppliers = new SelectList(await supplierRepo.GetSuppliersRepo(await CheckAuth()), "SupplierId", "SupplierName");

            return View(product);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int ProductId)
        {
            // Fetch product from the repository
            var product = await repo.GetProductByIdAsync(ProductId);

            if (product == null)
            {
                return NotFound();
            }

            // Create a model for the view with the existing product data
            var model = new UpdateProductRequest
            {
                ProductId = product.ProductId,
                ProductName = product.ProductName,
                Price = product.Price,
                LowStock = product.LowStock,
                SubCategoryId = product.SubCategoryId,
                SupplierId = product.SupplierId,
                ApplicationUserId = await CheckAuth()
            };
            

            // Populate dropdowns if necessary (for example, subcategories or suppliers)
            ViewBag.SubCategories = new SelectList(await subCategoryRepo.GetSubCategoriesRepo(), "SubCategoryId", "SubCategoryName");
            ViewBag.Suppliers = new SelectList(await supplierRepo.GetSuppliersRepo(await CheckAuth()), "SupplierId", "SupplierName");

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(UpdateProductRequest model)
        {
            if (ModelState.IsValid)
            {
                // Handle file upload if there is a photo
                
                var res = await repo.UpdateProductAsync(model);

                if(res.Done)
                return RedirectToAction(nameof(GetAllProducts)); // Redirect to a list or details page after update


               
            }

            // Repopulate dropdowns if validation fails
            ViewBag.SubCategories = new SelectList(await subCategoryRepo.GetSubCategoriesRepo(), "SubCategoryId", "SubCategoryName");
            ViewBag.Suppliers = new SelectList(await supplierRepo.GetSuppliersRepo(await CheckAuth()), "SupplierId", "SupplierName");

            return View(model);
        }

        public async Task<IActionResult> DeleteProduct(int id)
        {
            var product = await repo.DeleteProductAsync(id);

            return RedirectToAction(nameof(GetAllProducts)); // Redirect to a list or details page after update

        }



        public async Task<IActionResult> Details(int id)
        {
            var product = await repo.GetProductByIdAsync(id);
            if (product == null)
            {

                return RedirectToAction(nameof(GetAllProducts));
            }
            return View(product);
        }
    }
}

InventoryManagementSystem/Controllers/ReportEndpoints/ReportController.cs
using IMS.Application.Interfaces.IEntitiesRepo;
using IMS.Domain.Entites;
using IMS.Persistance.Repositories.EntitiesRepo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static IMS.Application.Features.Product.ProductManagementModel;
using static IMS.Application.Features.Report.ReportManagementModel;

namespace InventoryManagementSystem.Controllers.ReportEndpoints
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ISupplierRepo supplierRepo;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IStockLevelRepo stockLevelRepo;
        private readonly IReportDashboardRepo repo;
        private readonly ISubCategoryRepo categoryRepo;

        public ReportController(ISupplierRepo supplierRepo,UserManager<ApplicationUser> userManager,IStockLevelRepo stockLevelRepo,IReportDashboardRepo repo,ISubCategoryRepo categoryRepo)
        {
            this.supplierRepo = supplierRepo;
            this.userManager = userManager;
            this.stockLevelRepo = stockLevelRepo;
            this.repo = repo;
            this.categoryRepo = categoryRepo;
        }
        private async Task<string> CheckAuth()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);

            return user.Id;

        }
        [HttpGet]
        public async Task<IActionResult> FilterReportView1()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FilterReportView1(FilterReports filter)
        {
            return RedirectToAction(nameof(GetReportHasProducts), filter);
        }

        [HttpGet]
        public async Task<IActionResult> GetReportHasProducts(FilterReports filter)
        {
            ViewBag.SubCategories = new SelectList(await categoryRepo.GetSubCategoriesRepo(), "SubCategoryId", "SubCategoryName");

            var res = await repo.GetReportProductAsync(filter);

            return View(res);
        }

        [HttpGet]
        public async Task<IActionResult> GetStockLevelReport(int id)
        {
            var stockLevels = await stockLevelRepo.GetStockLevelsByProductIdAsync(id);
            ViewBag.CurrentStock = await stockLevelRepo.GetCurrentStockAsync(id);
            //var pro = await productRepo.GetProductByIdAsync(id);
            //ViewBag.Id = id;

            return View(stockLevels);
        }


        public async Task<IActionResult> GetAllSuppliersReport()
        {
            var suppliers = await supplierRepo.GetSuppliersRepo(await CheckAuth());
            return View(suppliers);
        }
        public class ReportViewModel
        {
            public IEnumerable<GetProductsResponse> Products { get; set; }
            public IEnumerable<GetCategoriesToAllPRoductsResponse>? Categories { get; set; }
        }
        public async Task<IActionResult> GetSupplierHasProductsReport(int id)
        {
            var products = await repo.GetProductsBySupplierIdAsync(id);
         
            return View(products);
        }

        public async Task<IActionResult> GetProductsByCategoryId(int id)
        {
            var products = await repo.GetProductsByCategoryIdAsync(id);

            return View(products);
        }
       

    }
}

InventoryManagementSystem/Controllers/StockLevelEndpoints/StockLevelController.cs
using IMS.Application.Interfaces.IEntitiesRepo;
using IMS.Domain.Entites;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using static IMS.Application.Features.Product.ProductManagementModel;
using static IMS.Application.Features.Report.ReportManagementModel;
using static IMS.Application.Features.StockLevel.StockLevelManagementModel;

namespace InventoryManagementSystem.Controllers.StockLevelEndpoints
{
    [Authorize]
    public class StockLevelController : Controller
    {
        private readonly IReportDashboardRepo dashboardRepo;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IStockLevelRepo repo;
        private readonly IProductRepo productRepo;

        public StockLevelController(IReportDashboardRepo dashboardRepo ,UserManager<ApplicationUser> userManager,IStockLevelRepo repo,IProductRepo productRepo)
        {
            this.dashboardRepo = dashboardRepo;
            this.userManager = userManager;
            this.repo = repo;
            this.productRepo = productRepo;
        }
        // View stock levels for a specific product
        private async Task<string> CheckAuth()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);

            return user.Id;

        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var stockLevels = await repo.GetStockLevelsByProductIdAsync(id);
            ViewBag.CurrentStock = await repo.GetCurrentStockAsync(id);
            var pro = await productRepo.GetProductByIdAsync(id);
            ViewBag.Id = id;
           
            return View(stockLevels);
        }

        // Update stock for a product
        [HttpGet]
        public async Task<IActionResult> AddOperationOnStockOfProduct(int id,bool sell)
        {
            var pro = await productRepo.GetProductByIdAsync (id);
            ViewBag.CurrentStock = await repo.GetCurrentStockAsync(id);

            var sto = new AddStockLevelRequest
            {
                DateUpdated = DateTime.UtcNow,
                ProductId = id,
                Quantity = 0,
                Sell = sell
            };
           


            return View(sto);
        }
        [HttpPost]
        public async Task<IActionResult> AddOperationOnStockOfProduct(AddStockLevelRequest model)
        {
            ViewBag.CurrentStock = await repo.GetCurrentStockAsync(model.ProductId);
            if (ModelState.IsValid)
            {
                var CurrentStock = await repo.GetCurrentStockAsync(model.ProductId);
                if(model.Sell && model.Quantity > CurrentStock)
                {
                    ModelState.AddModelError("", "Quantity Large from CurrentStock");
                    return View(model);
                }
                await repo.AddStockLevelAsync(model,await CheckAuth());
                return RedirectToAction(nameof(Details),new { id = model.ProductId });
            }
            return View(model);
        }

        public class ReportViewModel
        {
            public IEnumerable<GetProductsResponse> Products { get; set; }
            public IEnumerable<GetCategoriesToAllPRoductsResponse> Categories { get; set; }
        }
        [HttpGet]
        public async Task<IActionResult> GetProductsAreLowStock()
        {
            var products = await repo.GetProductsAreLowStockAsync(await CheckAuth());
            var cats = await dashboardRepo.GetCategoriesToAllPRoductsAsync(await CheckAuth());

            var models = new ReportViewModel
            {
                Products = products,
                Categories = cats
            };
            return View(models);

        }
        //[HttpGet]
        //public async Task<IActionResult> GetCategoriesToAllPRoducts()
        //{
        //    var cats = await dashboardRepo.GetCategoriesToAllPRoductsAsync(await CheckAuth());

        //    return PartialView("~/Views/Report/GetCategoriesToAllPRoducts.cshtml", cats);
        //}


    }
}

InventoryManagementSystem/Controllers/SupplierEndpoints/SupplierController.cs
using IMS.Application.Interfaces.IEntitiesRepo;
using IMS.Domain.Entites;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using static IMS.Application.Features.Supplier.SupplierManagementModel;

namespace InventoryManagementSystem.Controllers.SupplierEndpoints
{
    [Authorize]
    public class SupplierController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ISupplierRepo repo;

        public SupplierController(UserManager<ApplicationUser> userManager,ISupplierRepo repo)
        {
            this.userManager = userManager;
            this.repo = repo;
        }

        private async Task<string> CheckAuth()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);

            return user.Id;

        }
        public async Task<IActionResult> GetAllSuppliers()
        {
            var suppliers = await repo.GetSuppliersRepo(await CheckAuth());
            return View(suppliers);
        }

        public IActionResult AddSupplier()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddSupplier(AddSupplierRequest supplier)
        {
            if (ModelState.IsValid)
            {
                await repo.AddSupplierAsync(supplier, await CheckAuth());
                return RedirectToAction(nameof(GetAllSuppliers));
            }
            return View(supplier);
        }

        public async Task<IActionResult> UpdateSupplier(int id)
        {
            var supplier = await repo.GetSupplierByIdAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            var sup = new UpdateSupplierRequest
            {
                SupplierId = supplier.SupplierId,
                SupplierName = supplier.SupplierName,
                ContactInfo = supplier.ContactInfo
            };
            return View(sup);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSupplier(UpdateSupplierRequest supplier)
        {
            if (ModelState.IsValid)
            {
                await repo.UpdateSupplierAsync(supplier);
                return RedirectToAction(nameof(GetAllSuppliers));
            }
            return View(supplier);
        }


        public async Task<IActionResult> DetailsOfSupplier(int id)
        {
            var supplier = await repo.GetSupplierByIdAsync(id);
            if (supplier == null)
            {
                return RedirectToAction(nameof(GetAllSuppliers));
            }

            return View(supplier);
        }

        public async Task<IActionResult> DeleteSupplier(int id)
        {
            await repo.DeleteSupplierAsync(id);
            return RedirectToAction(nameof(GetAllSuppliers));
        }

    }
}

InventoryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AZA Inventory Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryManagementSystem.styles.css" asp-append-version="true" />
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            background-color: #f8f9fa;
            color: #343a40;
        }

        .navbar {
            background-color: #DEB887; 
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .navbar-brand img {
            height: 40px; 
        }

        .navbar-nav .nav-item {
            margin-left: 15px; 
        }

        .navbar-nav .nav-link {
            color: #fff; 
            padding: 10px 20px; 
            border-radius: 0.25rem; 
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        .navbar-nav .nav-link:hover {
            background-color: #FFD700; 
            color: #000; 
        }

        .footer {
            padding: 10px 0;
            margin-top: 20px;
            border-top: 1px solid #DEB887; 
        }

        .footer a {
            color: #007bff;
        }

        .footer a:hover {
            text-decoration: underline;
        }

        .dropdown-menu {
            background-color: #DEB887; 
        }

        .dropdown-item {
            color: #fff; 
        }

        .dropdown-item:hover {
            background-color: #FFD700; 
        }

        
      
            .navbar-brand img {
                height: 30px; 
            }
        
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="StockLevel" asp-action="GetProductsAreLowStock">
                    <img src="~/Files/Images/logo.png" alt="AZA Logo" />
                    <label> Aza</label>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="GetAllProducts">Products</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Reports
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="GetReportHasProducts">Report about Products</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="GetAllSuppliersReport">Report about Suppliers</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Supplier" asp-action="GetAllSuppliers">Suppliers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container my-4">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container text-center">
            &copy; 2024 - AZA Inventory Management System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>